www.dd528.com:
  datamodule: ['ProductModel', 'ProductPrice']
  callback:
    classinfo:
      modulename: callbackdd528
      classname: Dd528Callback
    httpinfo:
      login_http:
        data_type: null
        callbackfunc: null
        generatorfunc: login_url_generator
      data_http:
        data_type: json
        callbackfunc: convert_data
        generatorfunc: data_url_generator
  row_def:
    path: '/D[data]'
  col_def:
    productid: '/D[id]'
    productclass: '/D[firstCatalogId]'
    productsize: '/D[specification]'
    productname: '/D[name]'
    productunit: '/D[unit]'
    productdate: '/D[produceDate]'
    productstarttime: '/D[startTime]'
    productendtime: '/D[endTime]'
    productleft:  '/D[left]'
    productlimit:  '/D[limit]'
    productorderlimit:  '/D[orderLimit]'
    productsales: '/D[sales]'
    productamount: '/D[amount]'
    productonsalestatus: '/D[onSellStatus]'
    productonsale: '/D[onSale]'
    productimgrl: '/D[imagePath]/L[0]'
    productprice: '/D[price]'
    productvipprice: '/D[vipPrice]'
  col_calc:
    product_url: ['calc_product_url', 'productid']
    product_brand: ['map_product_brand', 'productname']
    product_spec: ['map_product_spec', 'productsize', '0']
    product_qty: ['map_product_spec', 'productsize', '1']
    product_lmt: ['map_product_spec', 'productsize', '2']
    product_taste: ['map_product_taste', 'productname']
    public_date: ['map_today']
pcshop.huimin100.cn:
  datamodule: ['ProductModel', 'ProductPrice']
  callback:
    classinfo:
      modulename: callbackhuimin
      classname: HuiminCallback
    httpinfo:
      login_http:
        data_type: null
        callbackfunc: null
        generatorfunc: login_url_generator
      data_http:
        data_type: html
        callbackfunc: convert_data
        generatorfunc: data_url_generator
  row_def:
    path: '//div[contains(@class,"goods_item") and contains(@class,"shenceView")]'
  col_def:
    productid: './@data-pid'
    productclass: './@data-classid'
    productsize: './@data-norm'
    productname: './@data-name'
    productunit: './@data-unit'
    product_lmt: './@data-prominnum'
    productboxnum: './@data-boxnum'
    productleft: './@data-minstroenum'
    productiscoupon: './@data-is_coupon'
    productisreturn: './@data-is_return'
    productprice: './@data-price'
    productsaleprice: './@data-saleprice'
  col_calc:
    product_url: ['calc_product_url', 'productid']
    product_brand: ['map_product_brand', 'productname']
    product_spec: ['map_product_spec', 'productsize', '0']
    product_qty: ['map_product_spec', 'productsize', '1']
    product_taste: ['map_product_taste', 'productname']
    public_date: ['map_today']
    productbrand: ['calc_cate_name', '%CATEGORYID%']
zgb.m.jd.com:
  datamodule: ['ProductModel', 'ProductPrice']
  callback:
    classinfo:
      modulename: callbackjd
      classname: JDCallback
    httpinfo:
      login_http:
        data_type: null
        callbackfunc: null
        generatorfunc: login_url_generator
      data_http:
        data_type: json
        callbackfunc: convert_data
        generatorfunc: data_url_generator
  row_def:
    path: '/D[data]/D[wareInfoList]'
  col_def:
    productid: '/D[skuId]'
    productclass: '/D[firstCatId]'
    productsize: '/D[packageSize]'
    productname: '/D[name]'
    productunit: '/D[saleUnit]'
    product_lmt: '/D[lowPurchaseCount]'
    productsales: '/D[sales]'
    productisreturn: '/D[isSevenReturn]'
    productisshoworgprice: '/D[showOriginPrice]'
    productprice: '/D[price]'
    productsaleprice: '/D[jdPrice]'
  col_calc:
    product_url: ['calc_product_url', 'productid']
    product_brand: ['map_product_brand', 'productname']
    product_spec: ['map_product_spec', 'productsize', '0']
    product_qty: ['map_product_spec', 'productsize', '1']
    product_taste: ['map_product_taste', 'productname']
    public_date: ['map_today']
www.dianjia.com:
  datamodule: ['ProductModel', 'ProductPrice']
  callback:
    classinfo:
      modulename: callbackdianjia
      classname: DianJiaCallback
    httpinfo:
      login_http:
        data_type: null
        callbackfunc: null
        generatorfunc: login_url_generator
      data_http:
        data_type: json
        callbackfunc: convert_data
        generatorfunc: data_url_generator
  row_def:
    path: '/D[pageInfo]/D[list]'
  col_def:
    productid: '/D[id]'
    product_brand: '/D[brandName]'
    productclass: '/D[categoryName]'
    productsize: '/D[specifications]'
    productname: '/D[skuName]'
    productunit: '/D[unit]'
    productdate: '/D[shelfLife]'
    productleft:  '/D[stock]'
    product_lmt:  '/D[purchaseMinimum]'
    productorderlimit: '/D[purchaseMaximum]'
    productsales: '/D[salesNum]'
    productonsalestatus: '/D@[alesMode]'
    productonsale: '/D[isSaleOut]'
    productimgrl: '/D[imageUrls]/L[0]'
    productprice: '/D[originalPrice]'
    productvipprice: '/D[salesPrice]'
    productsaleprice: '/D[marketPrice]'
    productiscoupon: '/D[guideComment]'
  col_calc:
    product_url: ['calc_product_url', 'productid']
    product_spec: ['map_product_spec', 'productsize', '0']
    product_qty: ['map_product_spec', 'productsize', '1']
    product_taste: ['map_product_taste', 'productname']
    public_date: ['map_today']