ProductModel:
  PK: ['internal_id']
  cols:
    internal_id: ['tenant', 'website', 'productid']
    tenantalias: 1
    tenant: 1
    website: 1
    productid: 1
    productclass: 0
    productbrand: 0
    productname: 1
    productunit: 1
    productsize: 0
    productdate: 0
    productstarttime: 0
    productendtime: 0
    productleft: 0
    productlimit: 0
    productorderlimit: 0
    productsales: 0
    productamount: 0
    productonsalestatus: 0
    productonsale: 0
    productimgrl: 0
    product_url: 0
    product_spec: 0
    product_qty: 0
    product_lmt: 0
    product_brand: 0
    product_taste: 0
    productboxnum: 0
    productiscoupon: 0
    productisreturn: 0
    productisshoworgprice: 0
ProductPrice:
  PK: ['internal_id', 'public_date']
  cols:
    internal_id: ['tenant', 'website', 'productid']
    tenantalias: 1
    website: 1
    productprice: 1
    productvipprice: 0
    productsaleprice: 0
    public_date: 1