brand:
  - 农夫山泉
  - 百事可乐
  - 康师傅
  - 统一
  - 今麦郎
  - 旺仔
  - 伊利
  - 可口可乐
  - 王老吉
  - 中沃
  - 红牛
  - 加多宝
  - 娃哈哈
  - 百事可乐
  - 健力宝
  - 阿尔卑斯
  - 养元
  - 雀巢
  - 椰树
  - 达利园
  - 银鹭
  - 怡宝
  - 东鹏特饮
  - 三得利
  - 百岁山
  - 立顿
  - 达能饮料
  - 宜简
  - 天友
  - 绿杰
  - 妙记
  - 豆本豆
  - 火山鸣泉
  - 维他
  - 依能
  - 川之花
  - 脉动
  - 乐虎
  - 日加满
  - 优珍
  - 隆顺榕
  - 華旗
  - 华旗
  - 天喔茶庄
  - 美汁源
  - 碱法
  - 北冰洋
  - 六个核桃
  - 汇源
  - 天地精华
  - 露露
  - 椰树
  - 宝矿力
  - 屈臣氏
  - 悦活
  - 名仁
  - 秋林格瓦斯
  - 怡达
  - 昆仑山
  - 中粮
  - 信远斋
  - 开卫
  - 中茶
  - 桂格
  - 星巴克
  - 怪兽
  - 欢乐家
  - 椰泰
  - 润田
  - 冠芳
  - 维维
  - 优洋
  - 尚品习饮
  - 都乐
  - 慕赏
  - 美立方
  - 苏小呵
  - 清谷田园
  - 台椰
  - 依藤园
  - 澳圣园
  - 恒大球球
  - 燕东
  - 沁园春
  - 硒苗苗
  - 爱洛
  - 正广和
  - 乐镜宇
  - 红牛
  - 旺旺
  - 辣妹子
  - 珍果园
  - 今贝
  - 果倍爽
  - 椰岛
  - 万劲
  - 惠京
  - 格零宝
  - 依能
taste:
  - 柠檬
  - 青柠
  - 西柚
  - 白葡萄
  - 紫玉葡萄
  - 橙
  - 青苹果
  - 苹果
  - 苹果香蕉
  - 荔枝
  - 蜜桃
  - 梨
  - 芒果
  - 酸梅
  - 陈皮酸梅
  - 薄荷
  - 菠萝
  - 瓜拉娜
  - 番茄
  - 覆盆子
  - 水蜜桃
  - 奇异果
  - 西瓜
  - 樱桃
  - 桃子
  - 山楂
  - 白葡萄槐花
  - 红葡萄玫瑰
  - 蜂蜜柚子
  - 椰子
  - 柚子
  - 红葡萄
  - 橙子
  - 番茄草莓
  - 胡萝卜橙子
  - 雪梨
  - 酸枣
  - 草莓
  - 茉莉
  - 蜜桃乌龙
  - 香草