www.dd528.com>pagename:
  request:
    method: post
    kwargs:
      url: http://www.dd528.com/login
      headers:
        Host: www.dd528.com
        User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
        Accept: '*/*'
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Referer: http://www.dd528.com/login
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Connection: keep-alive
      data:
        uid: UXIXD
        pwd: PXWXD
        plugin[sw]: !!str 1366
        plugin[sh]: !!str 768
        plugin[iw]: !!str 1301
        plugin[ih]: !!str 274
        plugin[ua]: 'Mozilla/5.0+(X11;+Ubuntu;+Linux+x86_64;+rv:57.0)+Gecko/20100101+Firefox/57.0'
        auto: !!str false
        uname: jtwu
        pwd: !!str 123456
  control:
    loginid: jtwu
    proxy: 127.0.0.1:1080
    sleep: 0
    prompt: crawling page xxx
    locate:
      - uname:
          type: 'id'
          key: 'username'
          action: ['send_keys']
      - pwd:
          type: 'id'
          key: 'password'
          action: ['clear','send_keys']
      - submit:
          type: 'id'
          key: 'loginBtn'
          action: ['click']
