car.autohome.com.cn-brand:
  init_http:
    url: https://car.autohome.com.cn
    method: get
    headers:
      Host: car.autohome.com.cn
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: '*/*'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Content-Type: 'application/x-www-form-urlencoded; charset=UTF-8'
  data_http:
    url: https://car.autohome.com.cn/price/brand-%BRANDID%.html
    method: get
    headers:
      Host: car.autohome.com.cn
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Referer: https://car.autohome.com.cn/
car.autohome.com.cn-series:
  data_http:
    url: https://car.autohome.com.cn/price/series-%SERIESID%.html
    method: get
    headers:
      Host: car.autohome.com.cn
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Referer: https://car.autohome.com.cn/price/brand-%BRANDID%.html
car.autohome.com.cn-price:
  data_http:
    url: https://carif.api.autohome.com.cn/dealer/LoadDealerPrice.ashx
    method: get
    headers:
      Host: carif.api.autohome.com.cn
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: '*/*'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Referer: https://car.autohome.com.cn/price/series-%SERIESID%.html
    data:
      _callback: 'LoadDealerPrice'
      type: '1'
      seriesid: '%SERIESID%'
      city: '%CITYID%'
car.autohome.com.cn-dealer:
  data_http:
    url: https://dealer.autohome.com.cn/frame/car/GetDealerByCar
    method: get
    headers:
      Host: dealer.autohome.com.cn
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Referer: https://car.autohome.com.cn/price/series-%SERIESID%.html
    data:
      SeriesId: '%SERIESID%'
      ProvinceId: '%PROVINCEID%'
      CityId: '%CITYID%'