RUN:
  Autohome: ['car.autohome.com.cn-brand']
NORUN:
  Nordstrom-Beachbag: ['shop.nordstrom.com-1']
  Nordstrom-Backbag: ['shop.nordstrom.com-2']
  Nordstrom-AllBeautiy: ['shop.nordstrom.com-x']
  天津惠民: ['pcshop.huimin100.cn', {UXIXD: 'zzz', PXWXD: 'zzz'}]