pcshop.huimin100.cn:
  prod_details:
    - [tenantalias, tenantalias]
    - [internal_id, internal_id]
    - [product_brand, 品牌]
    - [productname, 商品名称]
    - [productbrand, 分类]
    - [product_spec, 规格]
    - [product_qty, 数量]
    - [product_lmt, 起订量]
    - [productunit, 单位]
    - [product_taste, 口味]
    - [productiscoupon, 促销]
    - [productleft, 库存]
    - [productisreturn, 退货]
    - [product_url, 商品链接]
  prod_price:
    - [tenantalias, tenantalias]
    - [internal_id, internal_id]
    - [public_date, public_date]
    - [productprice, 价格]
www.dd528.com:
  prod_details:
    - [tenantalias, tenantalias]
    - [internal_id, internal_id]
    - [product_brand, 品牌]
    - [productname, 商品名称]
    - [product_spec, 规格]
    - [product_qty, 数量]
    - [product_lmt, 起订量]
    - [productunit, 单位]
    - [product_taste, 口味]
    - [productdate, 生产日期]
    - [productleft, 库存]
    - [productsales, 销量]
    - [productstarttime, 上架时间]
    - [productendtime, 下架时间]
    - [productonsalestatus, 销售状态]
    - [productonsale, 促销]
    - [productorderlimit, 限购数量]
    - [product_url, 商品链接]
  prod_price:
    - [tenantalias, tenantalias]
    - [internal_id, internal_id]
    - [public_date, public_date]
    - [productprice, 价格]
    - [productvipprice, 会员价]
zgb.m.jd.com:
  prod_details:
    - [tenantalias, tenantalias]
    - [internal_id, internal_id]
    - [product_brand, 品牌]
    - [productname, 商品名称]
    - [product_spec, 规格]
    - [product_qty, 数量]
    - [product_lmt, 起订量]
    - [productunit, 单位]
    - [product_taste, 口味]
    - [productisshoworgprice, 显示原价]
    - [productsales, 销量]
    - [product_url, 商品链接]
  prod_price:
    - [tenantalias, tenantalias]
    - [internal_id, internal_id]
    - [public_date, public_date]
    - [productsaleprice, 京东价格]
    - [productprice, 价格]