# -*- coding: utf-8 -*-
shop.nordstrom.com-nobrowser:
  datamodule: ['ProductModel']
  callback:
    classinfo:
      modulename: callbacknds
      classname: NDSCallback
    httpinfo:
      init_http:
        data_type: null
        callbackfunc: null
        generatorfunc: init_url_generator
      data_http:
        data_type: json
        callbackfunc: convert_data
        generatorfunc: data_url_generator
      browser_http:
        data_type: html
        callbackfunc: null
        generatorfunc: browser_url_generator
  row_def:
    path: '/D[ProductData]/D[~$id]'
  col_def:
    prodbrandid: '/D[Brand]/D[Id]'
    prodbrandname: '/D[Brand]/D[Label]'
    prodid: '/D[Id]'
    prodname: '/D[Title]'
    prodmodel: '/D[StyleNumber]'
    productspec: ''
    prodpricemin: '/D[Prices]/L[0]/D[MinItemPrice]'
    prodpricemax: '/D[Prices]/L[0]/D[MaxItemPrice]'
    prodpricemincut: '/D[Prices]/L[-1]/D[MinItemPrice]'
    prodpricemaxcut: '/D[Prices]/L[-1]/D[MaxItemPrice]'
    prodimgurl: '/D[Media]/L[0]/D[Url]'
    prodreviewcnt: '/D[ReviewSummary]/D[ReviewsCount]'
    prodreviewrating: '/D[ReviewSummary]/D[AverageRating]'
    prodcolor_info: '/D[Colors]/L[:]/D[Name]'
    produrl_short: '/D[ProductPageUrl]'
  col_calc:
    prodcolor: ['get_join_color', 'prodcolor_info']
    sitename: ['get_dmap_param', '%SITENAME%']
    catal1: ['get_dmap_param', '%CATAL1%']
    catal2: ['get_dmap_param', '%CATAL2%']
    catal3: ['get_dmap_param', '%CATAL3%']
    prodimgfile: ['get_img_url', prodid, prodimgurl]
    produrl: ['get_prod_url', produrl_short]
shop.nordstrom.com-add:
  datamodule: ['ProductAddModel']
  callback:
    classinfo:
      modulename: callbacknds
      classname: NDSCallback
    httpinfo:
      init_http:
        data_type: null
        callbackfunc: null
        generatorfunc: init_prod_url_generator
      prod_http:
        data_type: html
        callbackfunc: null
        generatorfunc: null
      img_http:
        data_type: html
        callbackfunc: download_img_content
        generatorfunc: null
  row_def:
    path: '//html'
  col_def:
    productspec: './/div[@class="option-main-text"]/text()'
    productspec_price_orderwrong: './/meta[@itemprop="price"]/@content'
    #productdetailh1: './/div[contains(@class,"np-details-module") and contains(@class,"np-details-and-care")]/div[contains(@class,"module-heading")]//text()'
    #productdetailc1_list: './/div[contains(@class,"np-details-module") and contains(@class,"np-details-and-care")]/div[contains(@class,"module-content")]//text()'
  col_calc:
    prodid: ['get_dmap_param', '%PRODUCTID%']
    #productdetailc1: ['join_prod_details', 'productdetailc1_list']
    productspecprice: ['get_prod_spec_price', 'productspec_price_orderwrong']