shop.nordstrom.com:
  init_http:
    url: https://shop.nordstrom.com
    method: get
    headers:
      Host: shop.nordstrom.com
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: '*/*'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Referer: https://shop.nordstrom.com
      Content-Type: 'application/x-www-form-urlencoded; charset=UTF-8'
    proxy:  '127.0.0.1:1080'
  data_http:
    url: https://shop.nordstrom.com/api/c/%CATAL3_NAME%
    method: get
    headers:
      Host: shop.nordstrom.com
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: 'application/json'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Referer: https://shop.nordstrom.com/c/%CATAL3_NAME%
      Content-Type: 'application/json'
    data:
      origin: topnav
      cm_sp: '%CM_SP_INFO%'
      page: '%PAGEINDEX%'
      top: !!str 72
    proxy:  '127.0.0.1:1080'
  browser_http:
    url: '%PRODUCT_URL%'
    method: selenium
    proxy:  '127.0.0.1:1080'
  img_http:
    url: '%IMG_URL%'
    method: get
    headers:
      Host: n.nordstrommedia.com
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
    proxy:  '127.0.0.1:1080'
shop.nordstrom.com-nobrowser:
  init_http:
    url: https://shop.nordstrom.com
    method: get
    headers:
      Host: shop.nordstrom.com
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: '*/*'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Referer: https://shop.nordstrom.com
      Content-Type: 'application/x-www-form-urlencoded; charset=UTF-8'
    proxy:  '127.0.0.1:1080'
  data_http:
    url: https://shop.nordstrom.com/api/c/%CATAL3_NAME%
    method: get
    headers:
      Host: shop.nordstrom.com
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: 'application/json'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
      Referer: https://shop.nordstrom.com/c/%CATAL3_NAME%
      Content-Type: 'application/json'
    data:
      origin: topnav
      cm_sp: '%CM_SP_INFO%'
      page: '%PAGEINDEX%'
      top: !!str 72
    proxy:  '127.0.0.1:1080'
  browser_http:
    url: '%PRODUCT_URL%'
    method: selenium
    proxy:  '127.0.0.1:1080'
  img_http:
    url: '%IMG_URL%'
    method: get
    headers:
      Host: n.nordstrommedia.com
      User-Agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      Accept-Encoding: gzip, deflate, br
    proxy:  '127.0.0.1:1080'