ProductModel:
  PK: ['sitename', 'prodid']
  cols:
    sitename: 1
    catal1: 0
    catal2: 0
    catal3: 0
    prodbrandid: 0
    prodbrandname: 0
    prodid: 1
    prodname: 0
    prodmodel: 0
    productspec: 0
    prodcolor: 0
    prodpricemin: 0
    prodpricemax: 0
    prodpricemincut: 0
    prodpricemaxcut: 0
    produrl: 0
    prodimgurl: 0
    prodimgfile: 0
    prodreviewcnt: 0
    prodreviewrating: 0