pcshop.huimin100.cn:
  prod_details:
    - [tenantalias, tenantalias]
    - [internal_id, internal_id]
    - [product_brand, 品牌]
    - [productname, 商品名称]
    - [productbrand, 分类]
    - [product_spec, 规格]
    - [product_qty, 数量]
    - [product_lmt, 起订量]
    - [productunit, 单位]
    - [product_taste, 口味]
    - [productiscoupon, 促销]
    - [productleft, 库存]
    - [productisreturn, 退货]
    - [product_url, 商品链接]
  prod_price:
    - [tenantalias, tenantalias]
    - [internal_id, internal_id]
    - [public_date, public_date]
    - [productprice, 价格]