shop.nordstrom.com:
  prod_info:
    - [catal1, catal1]
    - [prodid, ProductId]
    - [catal2, 类别]
    - [catal3, 子类别]
    - [prodbrandname, 品牌]
    - [prodname, 产品名称]
    - [prodmodel, 型号]
    - [prodcolor, 颜色]
    - [prodpricemin, 价格min]
    - [prodpricemax, 价格max]
    - [prodpricemincut, 折扣价min]
    - [prodpricemaxcut, 折扣价max]
    - [produrl, 链接]
    - [prodreviewcnt, 评价数]
    - [prodreviewrating, 评价]
  prod_addinfo:
    - [prodid, prodid]
    - [productspec, 规格]
    - [productspecprice, 规格价格]