tmall.com:
  tmall_comment:
    - [sitename, 站点]
    - [internal_id, uuid]
    - [itemid, 商品Id]
    - [sellerid, 卖家Id]
    - [prodname, 商品名称]
    - [produrl, 商品链接]
    - [username, 昵称]
    - [golduser, 超级会员]
    - [ratedate, 评论日期]
    - [content, 评论内容]
    - [sku, SKU]
tmall.hk:
  tmall_comment:
    - [sitename, 站点]
    - [internal_id, uuid]
    - [itemid, 商品Id]
    - [sellerid, 卖家Id]
    - [prodname, 商品名称]
    - [produrl, 商品链接]
    - [username, 昵称]
    - [golduser, 超级会员]
    - [ratedate, 评论日期]
    - [content, 评论内容]
    - [sku, SKU]
liangxinyao.com:
  tmall_comment:
    - [sitename, 站点]
    - [internal_id, uuid]
    - [itemid, 商品Id]
    - [sellerid, 卖家Id]
    - [prodname, 商品名称]
    - [produrl, 商品链接]
    - [username, 昵称]
    - [golduser, 超级会员]
    - [ratedate, 评论日期]
    - [content, 评论内容]
    - [sku, SKU]
jd.com:
  jd_comment:
    - [sitename, 站点]
    - [internal_id, uuid]
    - [prodid, 商品Id]
    - [prodname, 商品名称]
    - [produrl, 商品链接]
    - [nickname, 昵称]
    - [userLevelId, 会员等级Id]
    - [userLevelName, 会员等级]
    - [creationTime, 评论日期]
    - [productColor, 商品颜色]
    - [productSize, 商品规格]
    - [score, 评分]
    - [content, 评论内容]
    - [replyCount, 回复数量]
    - [isMobile, 是否手机评论]
    - [userClientShow, 客户端类型]
    - [userExpValue, 会员经验值]
    - [plusAvailable, PLUS会员经验值]
yiyaojd.com:
  jd_comment:
    - [sitename, 站点]
    - [internal_id, uuid]
    - [prodid, 商品Id]
    - [prodname, 商品名称]
    - [produrl, 商品链接]
    - [nickname, 昵称]
    - [userLevelId, 会员等级Id]
    - [userLevelName, 会员等级]
    - [creationTime, 评论日期]
    - [productColor, 商品颜色]
    - [productSize, 商品规格]
    - [score, 评分]
    - [content, 评论内容]
    - [replyCount, 回复数量]
    - [isMobile, 是否手机评论]
    - [userClientShow, 客户端类型]
    - [userExpValue, 会员经验值]
    - [plusAvailable, PLUS会员经验值]
jd.hk:
  jd_comment:
    - [sitename, 站点]
    - [internal_id, uuid]
    - [prodid, 商品Id]
    - [prodname, 商品名称]
    - [produrl, 商品链接]
    - [nickname, 昵称]
    - [userLevelId, 会员等级Id]
    - [userLevelName, 会员等级]
    - [creationTime, 评论日期]
    - [productColor, 商品颜色]
    - [productSize, 商品规格]
    - [score, 评分]
    - [content, 评论内容]
    - [replyCount, 回复数量]
    - [isMobile, 是否手机评论]
    - [userClientShow, 客户端类型]
    - [userExpValue, 会员经验值]
    - [plusAvailable, PLUS会员经验值]